### ISSUE TITLE
page not loading properly and content not loading // http status 404 

### ISSUE THREAD

**Issue by deveshruttala** [shashirajraja/shopping-cart#16]
I have followed the instructions for installation from the youtube video  but I have come up with a problem of not loading some contexts in the page. 
i am not able to view the cart and login into the webpage and it show http response error 404 where pages are present but i am not able to access it 
i have connected the database properly  and have the requirements installed (screenshots given) 
product category not working 
i have installed this using git from the repo directly into eclipse 
_____

i am mainly getting a http 404 error , which is the following 

HTTP Status 404 – Not Found
Type Status Report

Message The requested resource [/shopping-cart/LoginSrv] is not available

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

**Screenshots**
![Screenshot 2023-10-17 135105](https://github.com/shashirajraja/shopping-cart/assets/45329115/dc549ce1-9ec6-4f17-b780-1a12f84dfe2d)
![Screenshot 2023-10-19 003329](https://github.com/shashirajraja/shopping-cart/assets/45329115/dfa10db2-f0c1-437b-9f79-d34c4682cd1a)
![Screenshot 2023-10-19 003414](https://github.com/shashirajraja/shopping-cart/assets/45329115/39894193-c2ea-4b21-8b8a-0ca435a51dca)
![Screenshot 2023-10-19 003502](https://github.com/shashirajraja/shopping-cart/assets/45329115/42f5fae7-7cf1-4d93-81bb-4453d1a0ab99)
![Screenshot 2023-10-17 133846](https://github.com/shashirajraja/shopping-cart/assets/45329115/1950df10-cc6a-4459-86a7-04be4c50a0e6)
![Screenshot 2023-10-17 133941](https://github.com/shashirajraja/shopping-cart/assets/45329115/8b6c2355-8f90-450e-aba7-6963bd14a0bf)
____________________________________________________________________________________________________________________
 - OS: windows 11
 - Browser - microsoft edge
 - tomcat version 10 
 - maven build vesion 4 
______________________________________________________________________________________________________________________________

console log: 
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version name:   Apache Tomcat/10.0.27
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Oct 3 2022 14:18:31 UTC
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version number: 10.0.27.0
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Windows 11
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            10.0
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          amd64
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             C:\Program Files\Java\jdk-20
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           20.0.2+9-78
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Oracle Corporation
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         C:\Users\rutta\eclipse-workspace\ecommerce\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         D:\devesh-coding\java-coding\tomcat\apache-tomcat-10.0.27
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=C:\Users\rutta\eclipse-workspace\ecommerce\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=D:\devesh-coding\java-coding\tomcat\apache-tomcat-10.0.27
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dwtp.deploy=C:\Users\rutta\eclipse-workspace\ecommerce\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dfile.encoding=UTF-8
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dstdout.encoding=UTF-8
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dstderr.encoding=UTF-8
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -XX:+ShowCodeDetailsInExceptionMessages
Oct 19, 2023 12:28:50 AM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [C:\Program Files\Java\jdk-20\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Java\jdk-20\bin;C:\Program Files\MySQL\mysql-connector-j-8.1.0\mysql-connector-j-8.1.0;C:\ApacheMaven\apache-maven-3.9.5-bin\apache-maven-3.9.5\bin;C:\Program Files\Git\cmd;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\rutta\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\rutta\AppData\Local\Programs\Python\Python312\;C:\Users\rutta\AppData\Local\Microsoft\WindowsApps;C:\Users\rutta\AppData\Roaming\npm;C:\Users\rutta\AppData\Local\GitHubDesktop\bin;C:\Users\rutta\AppData\Local\Programs\Microsoft VS Code\bin;.]
Oct 19, 2023 12:28:50 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Oct 19, 2023 12:28:50 AM org.apache.catalina.startup.Catalina load
INFO: Server initialization in [1502] milliseconds
Oct 19, 2023 12:28:50 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Catalina]
Oct 19, 2023 12:28:50 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/10.0.27]
Oct 19, 2023 12:28:51 AM org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
WARNING: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [131] milliseconds.
Oct 19, 2023 12:28:54 AM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Oct 19, 2023 12:28:54 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
Oct 19, 2023 12:28:54 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in [3581] milliseconds
.
.
.
.
.
.
i probably think database or install error or code error i am actually recieving 

please resolve this error in this project @shashirajraja @the-suman

**Comment by deveshruttala** [comment]
please resolve this http 404 error after performing installation from the yt video

**Comment by Nethaji-nethu** [comment]
Try running the project from the root Folder instead in eclips.

if you are manually deploying, then i am also facing the same issue here. i am trying to deploy the war file in a tomcat docker container into tomcat's webapps folder but after deploying, no JSP pages are served. All 404 errors. perhaps i should change the project name ??

**Comment by Nethaji-nethu** [comment]
I found my solution. i had a different name given like shopping-cart-0.0*SNAPSHOT.war something like that and when i deployed as is into the webapps folder, it extracted to same folder (shopping-cart-0.0*SNAPSHOT) and because of the dots (.) involved in it. it was unable to open and i was for most part browsing the wrong endpoint ( /shopping-cart ). so i finally renamed the war file to "shopping-cart.war" before deploying and it worked for me. but in eclips, i think it somehow resolves it all and works i guess.

FYI i already had the DB configured with correct root password and up. when not, i received error stating the "con" object is null. Which obviously was true.
